# Generated by Django 4.2.20 on 2025-08-21 13:22

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('usuario'), models.F('tipo'), name='uniq_categoria_usuario_nombre_ci_tipo'),
        ),
    ]
